version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    tty: true
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env
    # entrypoint: containers/django/entrypoint.sh

  postgres:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    # options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    depends_on:
      - postgres
    env_file:
      - .env
    
  react:
    build:
      context: .
      dockerfile: containers/react/Dockerfile
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    # command: sh -c "yarn dev"

volumes:
  postgres_data:
  pgadmin4_data:
