version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: containers/django/Dockerfile.prod
    tty: true
    volumes:
      - ./backend:/app
      # - backend/staticfiles:/app/staticfiles
      # - backend/mediafiles:/app/mediafiles
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env.prod
    networks:
      - backend_network
    # expose:
    # - "8000"
    # command: sh -c "/usr/local/bin/entrypoint.sh"
    # entrypoint: containers/django/entrypoint.sh

  postgres:
    image: postgres:15.2
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.prod
    networks:
      - backend_network
    # options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - pgadmin4_data_prod:/var/lib/pgadmin
    depends_on:
      - postgres
    env_file:
      - .env.prod
    networks:
      - backend_network
    
  react:
    build:
      context: .
      dockerfile: containers/react/Dockerfile
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    networks:
      - frontend_network
    # command: sh -c "yarn dev"
    environment:
      - DEBUG=0

  nginx_backend:
    container_name: nginx_backend
    # NginxのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: containers/nginx/backend/Dockerfile
    # ボリュームを指定
    # ローカルの/staticをコンテナの/staticにマウントする
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/mediafiles:/app/mediafiles
      # - media_volume:/media
    # ローカルの8080番ボートをコンテナの80番ポートとつなぐ
    ports:
      - "8080:80"
    # 先にdjangoを起動してからnginxを起動する
    depends_on:
      - django
    networks:
      - backend_network

  nginx_frontend:
    container_name: nginx_frontend
    # NginxのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: containers/nginx/frontend/Dockerfile
    # ボリュームを指定
    ports:
      - "80:80"
    # 先にreactを起動してからnginxを起動する
    depends_on:
      - react
    networks:
      - frontend_network

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge

volumes:
  postgres_data_prod:
  pgadmin4_data_prod:
